import { profileSchema } from "./schema";

export const profile = profileSchema.parse({
  name: "Olger Chotza",
  role: "Software Engineer, AI Platforms",
  locality: "Remote",
  country: "Greece",
  countryCode: "GR",
  email: "me@ochotzas.com",
  tagline: "I make the demo survive real users, then make it boring on purpose.",
  bio: [
    "I take software that half-works and make it hold, usually a PoC that found real users before it found an architecture, or an app vibe-coded into existence that breaks every time someone touches it. Clean, hexagonal boundaries, mostly: the business logic in the middle, everything else replaceable at the edges. The rest of my time goes to AI platforms, models served in-house, agents wired to tools that do real work. Mostly Python, with Next.js when the thing needs a face.",
    "Before that, cars. Test automation for telematics units that ship inside a Mercedes-Benz, vehicles flashed straight from a pipeline, and long arguments with ECUs that were simulated and no less stubborn for it. Automotive teaches you one thing fast: a flaky test isn't noise, it's a wrong answer about a two-tonne object. I pointed that instinct at AI, most recently at a robot arm, where the hardware team owns the kinetics and I own the part that reasons: it reads the screen, plans its way through a test case, executes, and replans when the screen disagrees, inside a safety kernel that keeps the steps that matter deterministic. The suites are natural language somebody wrote, or cases generated by another tool I built.",
    "I write a lot of Python, and these days I write it next to agents: Claude Code, Codex and Antigravity do the typing on the parts that deserve typing, while I keep the shape of the thing in my head where it belongs. I've shipped agents that review a merge request before any human sees it, and I spend a good share of my time taking apart codebases that were vibe-coded to a working demo and then stopped working.",
    "Everything on this page started as an irritation, something that should exist, doesn't, and looks suspiciously like one weekend of work. A few of them grew up. PromptKit was me refusing, one final time, to paste a prompt into a string literal.",
    "I start strange projects, lose interest, make coffee, come back. If you're wired the same way, let's build something before either of us remembers we were busy.",
  ],
  available: null,
});
